### PR TITLE
Fix #11 Visual Studio 2017 15.7

### LINKED ISSUE #11: Visual Studio 2017 version 15.7 no longer works
Many tags such as methods, extension methods and local variables colors stopped working.

### PR DESCRIPTION
**Pull request by Spaier**
Fixes an issue with extension not working in vs 15.7. In Visual Studio 2017 15.7 Property names, method names and etc. have ClassificationType "property name", "method name" and etc., not "identifier" while current code uses Convert method only for s.ClassificationType == "identifier" so everything except namespace identifiers and constructors were left out. 
Also I rewrote async code using `ConfigureAwait(false)` without `Task` because using `Task` and `async` methods without `ConfigureAwait(false)` can lead to deadlocks in synchronous context. Also with `ConfigureAwait(false)` we don't have to use `Task.WhenAll`.

### CODE REVIEW

**Review by Art-Stea1th — COMMENTED** [review]
Hello, Spaier. Thank you for finding the reason. I have a some question.

Old versions of the packages were used to support Visual Studio 2015. Are you sure that these new will work with VS 2015?

At this moment, I do not have the environment to check this, but I need to first make sure of this and check everything, after which I'll merge it into the "Master" (with some changes).

**Comment by Spaier** [comment]
I don't have vs2015 so I don't know. Tested it with vs2017 15.7 Enterprise and Community. I will check it with VS2015 Community Update 3.

**Comment by Spaier** [comment]
It didn't work at all in VS2015 - no user tags in font and colors. I'll revert package updates and see if it helps.
UPD: reverting packages fixed it for vs2015 and didn't break anything for vs2017.

**Comment by Spaier** [comment]
Reverted packages in order to make extension work in vs2015. Old `ClassificationTypeNames` (`class name`, `struct name` and etc.) should probably be excluded along with xml in order to prevent bugs with 2 different color from this extension and visual studio.

```csharp

// All constants from namespace Microsoft.CodeAnalysis.Classification in Microsoft.CodeAnalysis.Workspaces 2.8.0 ending with "name"
                // Included atm, old ones
                public const string ClassName = "class name";
		public const string DelegateName = "delegate name";
		public const string EnumName = "enum name";
		public const string InterfaceName = "interface name";
		public const string ModuleName = "module name";
		public const string StructName = "struct name";
		public const string TypeParameterName = "type parameter name";
                // Included atm, new ones
		public const string FieldName = "field name";
		public const string EnumMemberName = "enum member name";
		public const string ConstantName = "constant name";
		public const string LocalName = "local name";
		public const string ParameterName = "parameter name";
		public const string MethodName = "method name";
		public const string ExtensionMethodName = "extension method name";
		public const string PropertyName = "property name";
		public const string EventName = "event name";
                // this is ignored with !s.ClassicationType.StartsWith("xml")
		public const string XmlDocCommentAttributeName = "xml doc comment - attribute name";
		public const string XmlDocCommentName = "xml doc comment - name";
		public const string XmlLiteralAttributeName = "xml literal - attribute name";
		public const string XmlLiteralName = "xml literal - name";

```

**Comment by Art-Stea1th** [comment]
I checked, it looks good. After a while, I will release an update for the extension, thank you for the fixes.

**Pull request merged**
