### PR TITLE
Fix for update of VS2019 16.5 update

### PR DESCRIPTION
**Pull request by flaengel**

### CODE REVIEW

**Review by sharwell — APPROVED** [review]

**Comment by penCsharpener** [comment]
This still doesn't work for me though. At the same place I get a NotImplementedException leading to an AggregateException. I have to wrap `var modifier = ... ` in a try catch.

**Comment by sharwell** [comment]
@penCsharpener What symbol type do you have?

**Comment by penCsharpener** [comment]
Does this help? Not entirely sure what information you are asking for...
2020-03-20_061407_pn_ESH

**Comment by penCsharpener** [comment]
me stupid, I inverted the if statement...

**Comment by penCsharpener** [comment]
ok, just debug a bit more and this seems to work for me now. 
```c#
var modifier = symbol is INamespaceSymbol || symbol is ILocalSymbol ? DeclarationModifiers.None : DeclarationModifiers.From(symbol);
```

**Comment by Art-Stea1th** [comment]
Hello friends! Recently, I have very little free time. Thank you for the proposed fix, I will try to check it out as soon as possible and release it.

**Comment by Art-Stea1th** [comment]
Released some time ago.

https://marketplace.visualstudio.com/items?itemName=StanislavKuzmichArtStea1th.EnhancedSyntaxHighlighting

Thanks again, for your help with resolving this issue.

**Pull request merged**
