### PR TITLE
Fix: async issues

### PR DESCRIPTION
**Pull request by CAT-Solstice**
Hi !

I guess I have fixed some issues in your async / await model (and some others).
You may take a look and tell me what you think about it.

CAT-Solstice, a user.

### CODE REVIEW

**Comment by Art-Stea1th** [comment]
Hi!

Yes, there were indeed issues when in some cases, the syntax highlighting was not applied completely to the last editing of the code until its next editing, this was because there was no guarantee of which of the threads would complete its execution first.

Now it looks great. I will merge these changes into the "master" branch, if you don't mind, and after a some cosmetic fixes I will release an update.

Thank you for your contribution.

**Comment by Art-Stea1th** [comment]
I could add you as a collaborator, but GitHub tells me: "CAT-Solstice is not a GitHub member".

adding-err
It seems that you have not completed the registration procedure. If you do this, I think I could fix this situation if necessary.

Once again, thank you for your contribution.

**Comment by CAT-Solstice** [comment]
Hi!

Nice to see you validate the fix.
I don't know why GitHub tells you I'm not a member, may be because the account is fresh ? I'm new to GitHub.

Regards,

**Comment by Art-Stea1th** [comment]
No, such settings are disabled in this repository.
settings-section
I was not allowed to add because I didn't quite do it right, I just had to specify the username and not the link to the page.

Now, it looks good, you only need to accept the invitation.
invite

Regards,

**Comment by CAT-Solstice** [comment]
Should be done.

Regards,

**Comment by Art-Stea1th** [comment]
Could you also read the information on [this page](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/).

It seems to me that you have some issues with the binding of the e-mail address, or contributions haven't been displayed [here](https://github.com/CAT-Solstice), as well as [here](https://github.com/Art-Stea1th/Enhanced-Syntax-Highlighting/graphs/contributors), because they are from another fork and not from another branch of this repository. (displayed only [here](https://github.com/Art-Stea1th/Enhanced-Syntax-Highlighting/commits/master), but the author isn't recognized).
unrecognized
Because, usually, even if commits have been added to another branch, they usually become visible after the merge into the "master" branch.

In any case, in the future, it will be easier for you to make changes, because now you are a collaborator. If necessary, you can create a branch directly in this repository, make changes, after which we will be able to merge with the "master" branch after validation.

Regards,

**Comment by CAT-Solstice** [comment]
I don't know what I should see related to this contribution, thank you for paying attention to it.

Here is what I see on my page (dunno why 3 contributions, but still...) :
github-contrib
May be related to the default "Contribution settings".

Regarding the "unrecognized author", I seems a mess between Microsoft (Visual Studio) account and the GitHub account. I have cloned (locally) your repo and done all commit (locally) before creating the GitHub account. Only after this, when I wanted to do a pull request, I created the GitHub account, fork your repo and I had to modify manually the .git/config to update my credentials and be able to push my branch on my repo (then do a pull request).

Again, thank you for paying attention to my contribution.

Regards,

**Comment by Art-Stea1th** [comment]
No, "Contribution Settings" only affects whether your commits in private repositories will be displayed for others. If everything was right, you should have 6 more commits in addition to the 3 existing ones, since this repository is public.

However, I think you are right, you fixed the .gitconfig, but commits has already been done to that time with the old credentials. And during the synchronization they were sent.

The main thing is so that at the time of the commit, the [e-mail address in the settings of the tool](https://help.github.com/articles/setting-your-commit-email-address-in-git/) that you use to interact with GitHub repository have matched with [e-mail address of your GitHub profile](https://github.com/settings/emails).

This shouldn't depends on the Visual Studio account address, and the username can be different even for each commit, but the GitHub e-mail address should match!

In this case everything should be fine ;)

When in the future you'll configure your tool to interact with git to make sure that this time everything is working correctly, you can create a test repository on your GitHub account, then clone it on a PC, then commit one or more local changes and synchronize them with the remote test repository.

If after these actions your activity from PC appears on your GitHub page as green squares, as well as the author of the commits will be with the correct profile image and click on the name will lead to your profile page - it means that now everything is fine! And for commits in the future this should remain the same.

After that, you can delete the test repository.
(test activity in this case should be automatically deleted from the profile).

P.S. For projects in Visual Studio with GitHub, I use a very simple but very powerful [GitHub extension](https://visualstudio.github.com/).

With it, there is no need to use git-bash or github-desktop or git-for-windows (I usually decline the Visual Studio offer to install the last from this list).

I hope this information will be useful for you.

Regards,

**Comment by CAT-Solstice** [comment]
Thanks for your insights about GitHub. I will try with my own repo to check if all is going well.

I'm using Visual Studio 2017 end-to-end, no third-party tool or extension, since it supports git natively now through Team Explorer.

Regards,

**Pull request merged**
